POS-130 - Fuzz tests
0xPolygon/pbft-consensus pull request #17
Opened 2022-01-20 09:02 UTC by 0xSasaPrsic

Added fuzz tests for PBFT.

2022-01-20 09:21 UTC, ferranbt requested changes

2022-01-20 09:21 UTC, ferranbt commented on e2e/fuzz_unreliable_network_test.go
> +		fmt.Printf("Checking for height %v, started with nodes %d\n", currentHeight, nodesCount)
Use `t.Log` instead of Print.

2022-01-20 09:21 UTC, ferranbt commented on e2e/fuzz_unreliable_network_test.go
> +	rand.Seed(time.Now().Unix())
Add a condition to only enabled this if `FUZZ` env variable is set.

2022-01-20 09:57 UTC, 0xSasaPrsic commented on e2e/fuzz_unreliable_network_test.go
> +		fmt.Printf("Checking for height %v, started with nodes %d\n", currentHeight, nodesCount)
Done.

2022-01-20 13:35 UTC, ferranbt commented on e2e/fuzz_unreliable_network_test.go
> +	rand.Seed(time.Now().Unix())
Add this into a function
```
func isFuzzEnabled(t *testing.T) {
        if os.Getenv("FUZZ") != "true" {
		t.Skip("Fuzz tests are disabled.")
	}
}
```

2022-01-20 13:37 UTC, ferranbt commented
Could you enable fuzz tests in CI:
- Add a new command `make fuzz` that only runs the Fuzz tests (`--run Fuzz`)
- Add a parallel fuzz task in Github that only runs the fuzz tests with some 10m timeout.

2022-01-21 09:04 UTC, ferranbt approved these changes

2022-01-21 10:35 UTC, merged